# Generated by Django 5.0.3 on 2024-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_description', models.CharField(null=True)),
                ('subscriptions', models.ManyToManyField(to='chat.user')),
            ],
        ),
    ]
