# Generated by Django 5.0.3 on 2024-04-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatspace_chat_name_alter_chatspace_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatspace',
            old_name='is_private',
            new_name='chat_type',
        ),
    ]
