# Generated by Django 5.0.3 on 2024-04-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_is_private_chatspace_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatspace',
            name='chat_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
