# Generated by Django 5.0.3 on 2024-04-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_chat_id_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatspace',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
