# Generated by Django 5.0.3 on 2024-05-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_message_chat_rename_has_avatar_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='privatechat',
            table='chat_private_chat',
        ),
        migrations.AlterModelTable(
            name='publicchat',
            table='chat_public_chat',
        ),
    ]
