# Generated by Django 5.0.3 on 2024-05-08 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_message_type_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
