# Generated by Django 5.0.3 on 2024-04-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chat',
            new_name='chats',
        ),
    ]
