# Generated by Django 5.0.3 on 2024-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rename_chat_user_chats'),
        ('chat', '0009_rename_subscriptions_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(related_name='users', to='chat.chatspace'),
        ),
    ]
