# Generated by Django 5.0.3 on 2024-05-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_user_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
